name             'linux_acl'
maintainer       'CloudGuy'
maintainer_email 'trijit@gmail.com'
license          'All rights reserved'
description      'Installs/Configures linux_acl'
long_description 'Installs/Configures linux_acl'
version          '0.1.0'
